name: Daily green square

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: daily-green
  cancel-in-progress: false

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - id: ts
        run: |
          echo "TZ=America/Denver" >> $GITHUB_ENV
          NOW="$(date +"%Y-%m-%d %H:%M:%S %Z")"
          TODAY="$(date +%F)"
          echo "now=$NOW" >> $GITHUB_OUTPUT
          echo "today=$TODAY" >> $GITHUB_OUTPUT

      - run: |
          FILE=heartbeat.txt
          touch "$FILE"
          if grep -q "^${{ steps.ts.outputs.today }} " "$FILE"; then
            echo "skip_commit=true" >> $GITHUB_ENV
            exit 0
          fi
          echo "${{ steps.ts.outputs.today }} – ${{ steps.ts.outputs.now }}" >> "$FILE"
          tail -n 365 "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"

      - if: env.skip_commit != 'true'
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add heartbeat.txt
          git commit -m "chore: daily heartbeat ${{ steps.ts.outputs.today }}"
          git push
